### ISSUE TITLE
update for upstream algorithm changes

### ISSUE THREAD

**Issue by dgryski** [dgryski/go-t1ha#1]
The hash function has changed since this port was done. Update to maintain compatibility.

**Comment by erthink** [comment]
There no changes in the algorithm, but function names have been revised.

Briefly, I considered useful the t1ha0, t1ha1, t1ha2...t1ha7 scheme, where a digit corresponds 'a level of quality'.

Now only t1ha0() and t1ha1() are available, and t1ha is a nickname of t1ha1.

**Comment by dgryski** [comment]
ah, ok.  I guess I'll close this then.  (I remember seeing a bunch of commits a while ago, and forgot to file a bug to remind myself to maintain compatibility.)
